integration_name: com.newrelic.memcached

instances:
  - name: memcached
    # Command can be all_data, metrics, or inventory
    command: all_data
    arguments:
      # Hostname of the memcached instance.
      # Defaults to localhost.
      host: mc-14-1
      # Port memcached is running on.
      # Defaults to 11211
      port: 11211
      # Memcached SASL username. Only required if
      # authentication is enabled.
      username: mc-7vpDG
      # Memcached SASL password. Only required if
      # authentication is enabled.
      password: yI4Uzs7nngIMbWlwegBDxnFZEMTTkpIX
